version: "3.9"

services:
  web:
    build:
      context: D:\\Projects\\_GIT\\_public\\Django_freelance
      dockerfile: Dockerfile.prod
    command: gunicorn django_freelance.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/django_freelance/web/staticfiles
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  nginx:
    build: nginx
    volumes:
      - static_volume:/home/django_freelance/web/staticfiles    
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: