# Generated by Django 3.2.9 on 2021-11-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0002_message_order_ordering_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='Ordering',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
